basePath: /api/v1
host: localhost:8080
info:
  contact:
    name: HETIC-MT5
  description: This is the api documentation for the CQRS Event sourcing implementation
    for HETIC
  license:
    name: MIT
  title: CQRS Event sourcing  documentation API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
